load_defaults: 7.19.2

development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://localhost:8983/solr/#TENANT#-public" %>
  # url: <%= ENV['SOLR_URL'] || "https://webapps.cspace.berkeley.edu/solr/#TENANT#-public" %>
  # url: <%= ENV['SOLR_URL'] || "https://apis.berkeley.edu/uat/cspace/v1/artifacts/#TENANT#-public" %>
  # nb: access via the api-central api using basicauth does not work yet: need to make a small change
  # in the configuration at api central to allow access to at least the select and suggest endpoints, and not
  # hide the endpoint completeley as we are doing now.
  # url: <%= ENV['SOLR_URL'] || "https://99999999:9999999999999999999@apis.berkeley.edu/uat/cspace/v1/artifacts/#TENANT#-public" %>
  # "app_id: 99999999"  "app_key: 9999999999999999999" get these from api-central or someone who has
  # calnet access to api-central.
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/pahma-public" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "https://webapps.cspace.berkeley.edu/solr/pahma-public" %>
  # url: <%= ENV['SOLR_URL'] || "http://localhost:8983/solr/#TENANT#-public" %>
  GLOBAL_ALERTS: <%= true %>
